# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include: [ '*' ]
  tags:
    include: [ 'release/*/*' ]
pr:
  branches:
    include: [ 'main', 'release/*' ]

variables:
  Codeql.Enabled: true

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build/azure-pipelines/win32/build.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: build/azure-pipelines/linux/build.yml

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: build/azure-pipelines/darwin/build.yml