package vscode:test-data

interface types {

	record point {
        x: u32,
        y: u32
	}

	call: func(point: point) -> u32;
	call-option: func(point: option<point>) -> option<u32>;

	resource point-resource {

        constructor(x: u32, y: u32);

        get-x: func() -> u32;
        get-y: func() -> u32;
        add: func() -> u32;
	}

	record point-option {
		x: option<u32>,
		y: option<u32>
	}

	variant test-variant {
		empty,
		unsigned32(u32),
		unsigned64(u64),
		signed32(s32),
		signed64(s64),
		floating-point32(float32),
		floating-point64(float64),
		structure(point),
	}
	check-variant: func(value: test-variant) -> test-variant;
}