package vscode:test

interface sample {

	record point {
        x: u32,
        y: u32
	}

	resource point-resource {

        constructor(x: u32, y: u32);

        get-x: func() -> u32;
        get-y: func() -> u32;
        add: func() -> u32;
	}

	call: func(point: point) -> u32;
	call-option: func(point: option<point>) -> option<u32>;
}